import type { Metadata } from "next";
import "../globals.css";
import { Poppins } from "next/font/google";


const poppins = Poppins({
    subsets: ["latin"],
    weight: "400",
});

export const metadata: Metadata = {
    title: "Create Web project",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" className=" scroll-smooth">
            <body
                className={`${poppins.className} antialiased capitalize`}
            >
                    {children}
            </body>
        </html>
    );
}
